### ISSUE TITLE
Version 1.0.3 on maven central misses BNB market

### ISSUE THREAD

**Issue by taniman** [webcerebrium/java-binance-api#1]
Could you please update the maven central version to include the BNB market in BinanceSymbol class

**Comment by wcrbrm** [comment]
hi @taniman 
please refer to version 1.0.5, it was just uploaded to maven central.

BNB market issues was fixed there
please consider also that there was little package renaming in the latest version - data types are separated from the API

thanks

**Comment by taniman** [comment]
thank you very much

**Comment by taniman** [comment]
Sorry to bother you, is there a waiting period before something is viewable on maven central?

![image](https://user-images.githubusercontent.com/6751341/33500899-dc213618-d6da-11e7-9ba2-4a77996277e3.png)

**Comment by wcrbrm** [comment]
Thanks for pointing that out, indeed, it seems the releasing process was not finished back then.

1.0.5 is still not visible on search.maven.org. but it is already resolving as dependency
https://oss.sonatype.org/content/groups/public/com/webcerebrium/binance-api/
http://repo1.maven.org/maven2/com/webcerebrium/binance-api/
