### ISSUE TITLE
BinanceApi::klines() and BinanceApi::aggTrades() seem buggy

### ISSUE THREAD

**Issue by Creckle** [webcerebrium/java-binance-api#11]
https://github.com/webcerebrium/java-binance-api/blob/db3378ef03c1e8752b6cee13087b1e5a3395a732/src/main/java/com/webcerebrium/binance/api/BinanceApi.java#L232

change 'or' to 'and'
same goes for 
https://github.com/webcerebrium/java-binance-api/blob/db3378ef03c1e8752b6cee13087b1e5a3395a732/src/main/java/com/webcerebrium/binance/api/BinanceApi.java#L181
and the next line

**Comment by wcrbrm** [comment]
@Creckle thanks for your feedback.

**Comment by wcrbrm** [comment]
the fix was included in Release 1.0.8, just pushed it on Maven
