### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by Diego1494** [webcerebrium/java-binance-api#20]
I believe that here:
https://github.com/webcerebrium/java-binance-api#using-api---placing-orders

The following:
BinanceOrder order = **api.getOrder**(symbol, api.createOrder(placement).get("orderId").getAsLong());
Should be changed to:
BinanceOrder order = **api.getOrderById**(symbol, api.createOrder(placement).get("orderId").getAsLong());

**Comment by wcrbrm** [comment]
nice notice, thanks
