### ISSUE TITLE
Get all prices return empty

### ISSUE THREAD

**Issue by hunghd60115** [webcerebrium/java-binance-api#21]
Hi,

Today below problem occurred. Could you please help me investigate this?

System.out.println((new BinanceApi()).allPrices());

-> 
12:51:16.964 [main] DEBUG com.webcerebrium.binance.api.BinanceRequest - GET https://www.binance.com/api/v1/ticker/allPrices
12:51:18.974 [main] DEBUG com.webcerebrium.binance.api.BinanceRequest - Response: []
[]

Best Regards,

**Comment by wcrbrm** [comment]
this might be related to the fact that Binance is on system maintenance
and unexpectedly lost some of their data ;)

They should resume at 2018/02/09 4AM (UTC) and may be it will work after that
