### ISSUE TITLE
getMinNotional Copy Paste Error Found

### ISSUE THREAD

**Issue by mustii82** [webcerebrium/java-binance-api#26]
<img width="733" alt="screenshot at feb 23 04-07-09" src="https://user-images.githubusercontent.com/12674597/36576144-1dbec378-184f-11e8-857f-7b06f31ea90d.png">

The Mistake is clear. Please correct the call fo Min Notional.

**Comment by shufps** [comment]
Oh coincidentally, I found the mistake today and opened an issue about the same :/

**Comment by wcrbrm** [comment]
the issue is fixed in 1.0.9 release
