### ISSUE TITLE
Logback 

### ISSUE THREAD

**Issue by stefanberg96** [webcerebrium/java-binance-api#32]
Hello,

I have been using this api for a little while now, and I like it. However I can not seem to disable the logback. I have never used logback myself, so I just tried creating logback.xml files at the root of the project and some other places. However it still keeps on logging. Can somebody tell me what I have to put where to disable it. I imported the project using maven.

**Comment by wcrbrm** [comment]
The first place to put the `logback.xml` is your java application resource folder, and not the root folder where you are running from - if you created a Kava project.

If you are using these library without creating a project, then root folder might work. Like it was done in Groovy examples - and there it does its job:
https://github.com/webcerebrium/java-binance-api/tree/master/examples

**Comment by stefanberg96** [comment]
Thank you very much this worked
