### ISSUE TITLE
ERROR: -1106, Parameter 'timeInForce' sent when not required.

### ISSUE THREAD

**Issue by spapapan** [webcerebrium/java-binance-api#8]
When I try to place an order using the  `BinanceOrderType.MARKET` I get the following error:

> com.webcerebrium.binance.api.BinanceApiException: ERROR: -1106, Parameter 'timeInForce' sent when not required.
> 	at com.webcerebrium.binance.api.BinanceRequest.read(BinanceRequest.java:260)
> 	at com.webcerebrium.binance.api.BinanceApi.createOrder(BinanceApi.java:498)

If I place an order through `BinanceOrderType.LIMIT` there is no problem.

**Comment by elsehow** [comment]
Looks like the API requires the `timeInForce` parameter *not* be sent for MARKET orders.

**Comment by chongjae** [comment]
I have same issue.
How can i fix it?

**Comment by wcrbrm** [comment]
@chongjae you can take the library from the sources. 
Fix would be included in an upcoming release this week and appear on maven central

**Comment by chongjae** [comment]
@wcrbrm 
Then, on this time, i can not fix it. Correct?
Dose this patch would be applied on 1.0.7?
Thanks.

**Comment by wcrbrm** [comment]
@chongjae
This patch will go to 1.0.8 which we are currently testing.

As alternative to maven central, you can always include library compiled from latest git source
https://github.com/webcerebrium/java-binance-api#with-latest-source-code

**Comment by pimp22** [comment]
Damn, I shouldve looked here earlier... Missing if in api. Any idea when this will be fixed? I dk how to compile with gradle. tried to click the file

**Comment by wcrbrm** [comment]
1.0.8 was published.
